apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - agent-server-istio.yaml

images:
  - name: 172.30.1.105:5000/fin-tech-sre/agent-server
    newTag: d08b72684dc1