prometheus:
  prometheusSpec:
    retention: 7d
    nodeSelector:
      node-role: observability
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      node-role: observability
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  enabled: true

  nodeSelector:
    node-role: observability

  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password

  initChownData:
    enabled: false
    image:
      registry: docker.io
      repository: library/busybox
      tag: "1.37.0"

  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

  containerSecurityContext:
    runAsUser: 472
    runAsGroup: 472
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false

  service:
    type: ClusterIP

kube-state-metrics:
  nodeSelector:
    node-role: observability

prometheus-node-exporter:
  tolerations:
    - operator: Exists
