prometheus:
  prometheusSpec:
    retention: 7d
    nodeSelector:
      node-role: observability
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      node-role: observability
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  enabled: true

  nodeSelector:
    node-role: observability

  persistence:
    enabled: true
    type: pvc
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: local-path

  initChownData:
    enabled: true

  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL

  adminUser: admin
  adminPassword: "ChangeMe-StrongPassword"

  service:
    type: ClusterIP

kube-state-metrics:
  nodeSelector:
    node-role: observability

prometheus-node-exporter:
  tolerations:
    - operator: Exists
